"""
Compute every RidgeBase metric from the saved result files and write a summary
(results/ridgebase/SUMMARY.md + summary_metrics.json). Runs standalone so the
numbers land on disk automatically when the benchmark finishes, ready to drop
into the paper.

For each model it reports, per comparison category:
  - Embedding (cosine) and Similarity-Scoring (prompt) AUC / EER
  - genuine vs primary_impostor (standard), same-device vs cross-device split,
    genuine vs diagnostic_impostor (mechanism)
  - binary prompts (zero_shot, task_description): FAR / accept-rate (collapse)

Missing files are skipped, so it is safe to run mid-benchmark.

Usage:  python code/analyze_ridgebase.py
"""
import glob, json, os
import numpy as np
import pandas as pd

RB = "results/ridgebase"
MODELS = ["qwen3vl", "qwen25vl", "internvl3", "gemma3", "anthropic", "openai"]
PAIRS = "results/ridgebase/pairs_ridgebase_eval.csv"


def auc_eer(pos, neg):
    if len(pos) == 0 or len(neg) == 0:
        return None, None
    from sklearn.metrics import roc_curve, auc as _auc
    y = np.r_[np.ones(len(pos)), np.zeros(len(neg))]
    s = np.r_[pos, neg]
    fpr, tpr, _ = roc_curve(y, s)
    a = _auc(fpr, tpr)
    fnr = 1 - tpr
    k = int(np.nanargmin(np.abs(fpr - fnr)))
    return round(float(a), 4), round(float((fpr[k] + fnr[k]) / 2) * 100, 2)


def cats(df, score):
    """Return the per-category metric dict from a df with category/device_pair/<score>."""
    g = df[df.category == "primary_genuine"][score].astype(float)
    pi = df[df.category == "primary_impostor"][score].astype(float)
    di = df[df.category == "diagnostic_impostor"][score].astype(float)
    gs = df[(df.category == "primary_genuine") & (df.device_pair == "same")][score].astype(float)
    gc = df[(df.category == "primary_genuine") & (df.device_pair == "cross")][score].astype(float)
    pis = df[(df.category == "primary_impostor") & (df.device_pair == "same")][score].astype(float)
    pic = df[(df.category == "primary_impostor") & (df.device_pair == "cross")][score].astype(float)
    std = auc_eer(g.values, pi.values)
    return {
        "n_genuine": int(len(g)), "n_impostor": int(len(pi)), "n_diag": int(len(di)),
        "genuine_mean": round(float(g.mean()), 3) if len(g) else None,
        "impostor_mean": round(float(pi.mean()), 3) if len(pi) else None,
        "standard_AUC": std[0], "standard_EER": std[1],
        "same_device_AUC": auc_eer(gs.values, pis.values)[0],
        "cross_device_AUC": auc_eer(gc.values, pic.values)[0],
        "diagnostic_AUC": auc_eer(g.values, di.values)[0],
    }


def load_prompted(model, strategy):
    fs = glob.glob(f"{RB}/{model}/latest/rb_{model}_{strategy}_*.csv")
    if not fs:
        return None
    return pd.read_csv(sorted(fs)[-1])


def analyze():
    out = {}
    for m in MODELS:
        rec = {}
        # embedding
        ef = f"{RB}/{m}/embed_{m}_eval.csv"
        if os.path.exists(ef):
            df = pd.read_csv(ef).dropna(subset=["cosine"])
            if "category" in df and len(df):
                rec["embedding"] = cats(df, "cosine")
        # similarity scoring
        ss = load_prompted(m, "similarity_score")
        if ss is not None and "similarity_score" in ss:
            ss = ss.dropna(subset=["similarity_score"])
            if len(ss):
                rec["similarity_scoring"] = cats(ss, "similarity_score")
        # binary collapse (FAR = accept-rate on impostor pairs)
        for strat in ("zero_shot", "task_description"):
            b = load_prompted(m, strat)
            if b is not None and "llm_answer" in b:
                imp = b[b.label == "non-mated"]
                gen = b[b.label == "mated"]
                if len(imp):
                    far = round(float((imp.llm_answer == "A").mean()) * 100, 1)
                    frr = round(float((gen.llm_answer == "B").mean()) * 100, 1) if len(gen) else None
                    rec.setdefault("binary", {})[strat] = {"FAR": far, "FRR": frr, "n": int(len(b))}
        if rec:
            out[m] = rec
    return out


def render_md(out):
    L = ["# RidgeBase Results Summary", "",
         "_Auto-generated by analyze_ridgebase.py. Genuine = independent captures; "
         "impostor device-matched to genuine._", "",
         "## Verification (genuine vs primary impostor)", "",
         "| Model | Embed AUC | Embed EER | SS AUC | SS EER | same-dev AUC | cross-dev AUC | diag AUC |",
         "|---|---|---|---|---|---|---|---|"]
    for m, r in out.items():
        e = r.get("embedding", {}); s = r.get("similarity_scoring", {})
        L.append(f"| {m} | {e.get('standard_AUC','—')} | {e.get('standard_EER','—')} | "
                 f"{s.get('standard_AUC','—')} | {s.get('standard_EER','—')} | "
                 f"{s.get('same_device_AUC', e.get('same_device_AUC','—'))} | "
                 f"{s.get('cross_device_AUC', e.get('cross_device_AUC','—'))} | "
                 f"{s.get('diagnostic_AUC', e.get('diagnostic_AUC','—'))} |")
    L += ["", "## Binary collapse (FAR = % of impostors accepted as 'same')", "",
          "| Model | ZS FAR | TD FAR |", "|---|---|---|"]
    for m, r in out.items():
        b = r.get("binary", {})
        L.append(f"| {m} | {b.get('zero_shot',{}).get('FAR','—')} | "
                 f"{b.get('task_description',{}).get('FAR','—')} |")
    return "\n".join(L) + "\n"


def main():
    global RB
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=RB, help="results tree, e.g. results/precise")
    a = ap.parse_args()
    RB = a.dir
    out = analyze()
    os.makedirs(RB, exist_ok=True)
    json.dump(out, open(f"{RB}/summary_metrics.json", "w"), indent=2)
    open(f"{RB}/SUMMARY.md", "w").write(render_md(out))
    print(render_md(out))
    print(f"saved -> {RB}/SUMMARY.md  and  summary_metrics.json")


if __name__ == "__main__":
    main()
